version: '3.7'
services:

  database:
    container_name: pg_container
    image: "postgres" # use latest official postgres version
    restart: always
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
    volumes:
      # persist data even if container shuts down
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./database_data:/var/lib/postgresql/data/
    # command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"

volumes:
      database_data:

